name: Bug Report
title: "Bug: "
description: Report a Bug
labels: ["kind/bug", "bug/unconfirmed"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug...
    validations:
      required: true
