name: Bug Report
title: "Bug: "
description: Report a Bug
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: Bug Report
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Type text here
    validations:
      required: true
