name: Task
title: "Task: "
description: Create a new Task
labels: ["kind/task", "status: open"]
assignees:
  - ztk37
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summarize the task...
    validations:
      required: true
