name: Task
title: "Task: "
description: Create a new Task
labels: ["kind/task", "status: open"]
assignees:
  - ztk37
body:
  - type: markdown
    attributes:
      value: New Task
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Type text here
    validations:
      required: true
