name: Umbrella
description: Sample description
labels: ["kind/umbrella"]
body:
  - type: markdown
    attributes:
      value: Umbrella
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Type text here
    validations:
      required: true
